/**
 * Bundles the TypeScript sources in src/ into the .user.js files Tampermonkey
 * installs. Those live at the repo root rather than in a dist/ directory: the
 * install route is "open the .user.js and confirm the prompt", so their URLs
 * are the product and moving them would break every existing install.
 *
 *   node build.mjs           bundle once
 *   node build.mjs --watch   rebuild on save
 *
 * Type checking is a separate step (`npm run typecheck`) - esbuild strips types
 * without looking at them, which is what makes it fast enough to run on save.
 */
import { build, context } from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));

/**
 * One entry per userscript. `meta` is the `// ==UserScript==` block; it is kept
 * as its own file rather than generated from fields here so that it stays
 * readable as what it is - Tampermonkey's own header format, copy-pasteable
 * into their docs and diffable against them.
 */
const TARGETS = [
  {
    entry: 'src/wanikani/main.ts',
    meta: 'src/wanikani/meta.js',
    outfile: 'wanikani-review-recap.user.js',
  },
];

const GENERATED = `
/*
 * Generated by \`npm run build\` from src/ - edit the modules there, not this
 * file. The comments that explain each piece live with the code they explain;
 * this bundle is the installable artefact, kept in the repository so the raw
 * URL stays a working install link.
 */
`.trimStart();

async function bannerFor(target) {
  const meta = await fs.readFile(path.join(ROOT, target.meta), 'utf8');
  // The metadata block has to come first for Tampermonkey to see it at all.
  return meta.trimEnd() + '\n\n' + GENERATED;
}

/** Shared by the one-shot and the watch build, so they cannot drift. */
async function optionsFor(target) {
  return {
    entryPoints: [path.join(ROOT, target.entry)],
    outfile: path.join(ROOT, target.outfile),
    bundle: true,
    format: 'iife',
    // Tampermonkey runs in current browsers; this is only a floor, not a
    // promise to support anything older.
    target: 'es2020',
    // Without this the Japanese in the panel (and in the CSS) is escaped to
    // \\uXXXX, which turns the readable half of the bundle into noise.
    charset: 'utf8',
    legalComments: 'none',
    banner: { js: await bannerFor(target) },
    logLevel: 'info',
  };
}

const watch = process.argv.includes('--watch');

for (const target of TARGETS) {
  const options = await optionsFor(target);
  if (watch) {
    const ctx = await context(options);
    await ctx.watch();
    console.log(`watching ${target.entry} -> ${target.outfile}`);
  } else {
    await build(options);
    const { size } = await fs.stat(path.join(ROOT, target.outfile));
    console.log(`${target.outfile}  ${(size / 1024).toFixed(1)} kB`);
  }
}
